name: flutter_paper_trail_plus
description: Elevate your app development experience with Flutter Paper Trail Plus. Seamlessly integrate advanced logging and real-time monitoring into your Flutter project. Swiftly identify and prioritize issues with enhanced logging, customizable outputs, and error notifications.
version: 1.0.0

homepage: https://github.com/mufassalhussain/flutter_paper_trail_plus
dependencies:
  meta: ^1.8.0
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterPaperTrailPlusPlugin
      android:
        package: com.mufassal.flutterpapertrailplus
        pluginClass: FlutterPaperTrailPlusPlugin

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"
